### ISSUE TITLE
Develop nodata-alpha command

### ISSUE THREAD

**Issue by sgillies** [mapbox/nodata#8]
Given a file that Rasterio can read and a nodata value (either in file metadata or from command line or API) produce a valid data mask. It should be general, robust, and fast, or at least make clear trade-offs  between these. We'll test it against the files in https://github.com/mapbox/nodata/tree/master/tests/fixtures/alpha.

Requirements (which may be modified):
- Command executes on EC2
- Command is installed in a virtualenv (it's in $PATH in other words)
- Command is deployed to the server as a binary, not compiled on the target
- Runs on Python versions 2.7 and 3.4

**Comment by dnomadb** [comment]
We made this in https://github.com/mapbox/rio-alpha!
